apiVersion: v1
kind: Secret
metadata:
  name: cnpg-superuser
  namespace: mynamespace
type: kubernetes.io/basic-auth
stringData:
  username: myname
  password: CHANGE_ME_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-app-user
  namespace: mynamespace
type: kubernetes.io/basic-auth
stringData:
  username: myname
  password: CHANGE_ME_PASSWORD